export const inviteEmailList = [
  { email: "Jasmin79@gmail.com", status: "Existing user" },
  { email: "Donnie_Jacobs@hotmail.com", status: "Existing user" },
  { email: "Shakira_Shanahan50@hotmail.com", status: "Success" },
  { email: "Verner.Cremin@yahoo.com", status: "Existing user" },
  { email: "Rickie.Paucek@yahoo.com", status: "Existing user" },
  { email: "Brown.Donnelly49@hotmail.com", status: "Invalid email" },
  { email: "Diana.Muller57@yahoo.com", status: "Success" },
  { email: "Jett24@yahoo.com", status: "Existing user" },
  { email: "Ansel19@gmail.com", status: "Success" },
  { email: "Maybell_Bernier50@yahoo.com", status: "Invalid email" },
  { email: "Assunta_Cremin@hotmail.com", status: "Success" },
  { email: "Hyman.Ebert@yahoo.com", status: "Invalid email" },
  { email: "Ima3@hotmail.com", status: "Success" },
  { email: "Elsa.Abbott@hotmail.com", status: "Invalid email" },
  { email: "Assunta.Thiel@yahoo.com", status: "Existing user" },
  { email: "Brown_Spinka@yahoo.com", status: "Invalid email" },
  { email: "Marianna_Kozey@gmail.com", status: "Existing user" },
  { email: "Aiden55@yahoo.com", status: "Success" },
  { email: "Lupe_Bruen4@hotmail.com", status: "Success" },
  { email: "Aimee_Will72@hotmail.com", status: "Invalid email" },
  { email: "Hiram_Feest@yahoo.com", status: "Success" },
  { email: "Duncan36@yahoo.com", status: "Invalid email" },
  { email: "Chelsey17@hotmail.com", status: "Success" },
  { email: "Brandon77@yahoo.com", status: "Invalid email" },
  { email: "Shemar25@yahoo.com", status: "Existing user" },
  { email: "Julius47@yahoo.com", status: "Invalid email" },
  { email: "Billy73@gmail.com", status: "Existing user" },
  { email: "Esteban_Kulas@hotmail.com", status: "Invalid email" },
  { email: "Gabriel.Kunde41@yahoo.com", status: "Success" },
  { email: "Branson.Kunze@gmail.com", status: "Success" },
  { email: "Jedediah.Watsica85@gmail.com", status: "Success" },
  { email: "Mavis33@gmail.com", status: "Existing user" },
  { email: "Catharine.Hane@yahoo.com", status: "Invalid email" },
  { email: "Jeanie_Larson7@yahoo.com", status: "Success" },
  { email: "Dedric80@hotmail.com", status: "Invalid email" },
  { email: "Henri.Anderson20@yahoo.com", status: "Success" },
  { email: "Allen_Kshlerin@yahoo.com", status: "Existing user" },
  { email: "Florencio_Goyette63@gmail.com", status: "Invalid email" },
  { email: "Merritt.Kiehn91@hotmail.com", status: "Existing user" },
  { email: "Hulda24@hotmail.com", status: "Success" },
  { email: "Vaughn.OConner69@gmail.com", status: "Invalid email" },
  { email: "Valerie.Bartoletti@yahoo.com", status: "Success" },
  { email: "Catalina33@gmail.com", status: "Existing user" },
  { email: "Emelie_Stokes@yahoo.com", status: "Invalid email" },
  { email: "Frances49@gmail.com", status: "Existing user" },
  { email: "Hudson_McLaughlin99@gmail.com", status: "Existing user" },
  { email: "Ruby69@hotmail.com", status: "Invalid email" },
  { email: "Nettie.Emard91@hotmail.com", status: "Invalid email" },
  { email: "Carlie.OHara@gmail.com", status: "Existing user" },
  { email: "Kelsie_Grimes@yahoo.com", status: "Existing user" },
];
